# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: true
warnings_are_errors: false
cache: packages

#r_binary_packages:
#  - libgit2

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
